* maybe blocking the export of a course because something went weired with the about   picture is excessive.
Handling the exception
AttributeError: 'Settings' object has no attribute 'DEFAULT_COURSE_ABOUT_IMAGE_URL'